export const taskActionTypes = {
	GET_LIST_TASK: "GET_LIST_TASK",
	GET_LIST_TASK_SUCCESS: "GET_LIST_TASK_SUCCESS",
	GET_LIST_TASK_FAILED: "GET_LIST_TASK_FAILED",
	ADD_NEW_TASK: "ADD_NEW_TASK",
	ADD_NEW_TASK_SUCCESS: "ADD_NEW_TASK_SUCCESS",
	ADD_NEW_TASK_FAILED: "ADD_NEW_TASK_FAILED",
	TOGGLE_ONE_TASK: "TOGGLE_ONE_TASK",
	TOGGLE_ONE_TASK_SUCCESS: "TOGGLE_ONE_TASK_SUCCESS",
	TOGGLE_ONE_TASK_FAILED: "TOGGLE_ONE_TASK_FAILED",
	DELETE_ONE_TASK: "DELETE_ONE_TASK",
	DELETE_ONE_TASK_SUCCESS: "DELETE_ONE_TASK_SUCCESS",
	DELETE_ONE_TASK_FAILED: "DELETE_ONE_TASK_FAILED",
};
